### ISSUE TITLE
Design mockup of the app

### ISSUE THREAD

**Issue by ferdouszislam** [NSU-SP21-CSE499-18/Group-01#14]
The mockup design using figma is optional since sir allowed it. However, we will need a rough sketch of the UI before starting to code.

**Comment by ferdouszislam** [comment]
figma link- https://www.figma.com/file/KqbhaqE5H0lMBtqqSl2ICA/AR-Book?node-id=0%3A1

**Comment by rifatislamomio** [comment]
Figma prototype modified and exported (.**png+ .fig**) to 'Mockup' folder.
