### ISSUE TITLE
Enhancement, UI: Create the App UI (XMLs in Android Studio)  

### ISSUE THREAD

**Issue by ferdouszislam** [NSU-SP21-CSE499-18/Group-01#16]
- Open the main Android Studio project (in Kotlin) named- "**AR Schoolbook**"
- Design the XML files for the App UI following the figma prototype- <https://www.figma.com/file/KqbhaqE5H0lMBtqqSl2ICA/AR-Book?node-id=0%3A1>.

**Comment by ferdouszislam** [comment]
@RifatIslamOmio please open the Android Studio porject named- "**AR Schoolbook**" and **select the language as Kotlin**.

Put the issue to "_In progress_" when you start.

**Comment by rifatislamomio** [comment]
Closing this issue for now. 
Reopen later for App Intro/Splash Screen.
Another issue will be created for linking Ui touch-ups.
